name: Wine-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test mobox
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build mobox
      run: |
        sudo apt-get -y install wget git autoconf debootstrap perl 
        git clone https://github.com/Kron4ek/Wine-Builds.git wine-builds
        cd wine-builds
        git clone https://github.com/wine-mirror/wine.git wine-src
        cd wine-src && git checkout stable
        patch -p 1 -i $GITHUB_WORKSPACE/patches/wine90.patch
        cd ..
        chmod +x create_ubuntu_bootstraps.sh & sudo ./create_ubuntu_bootstraps.sh
        chmod +x build_wine.sh && ./build_wine.sh
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./*.tar.xz
