name: Wine-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test mobox
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build mobox
      run: |
        sudo apt-get -y install wget git autoconf debootstrap perl bubblewrap 
        https://github.com/PSzczepanski1996/Wine-Builds.git wine-builds
        cd wine-builds
        git clone https://github.com/wine-mirror/wine.git wine-src
        cd wine-src && git checkout stable
        patch -p 1 -i $GITHUB_WORKSPACE/patches/wine90.patch
        cd ..
        chmod +x create_ubuntu_bootstraps.sh & sudo ./create_ubuntu_bootstraps.sh
        chmod +x build_wine.sh && ./build_wine.sh
    - uses: actions/upload-artifact@v4
      name: Upload Wine AMD64 build
      with:
        name: wine-amd64.tar.xz
        path: ./wine-builds/wine*amd64.tar.xz
    - uses: actions/upload-artifact@v4
      name: Upload Wine X86 build
      with:
        name: wine-x86.tar.xz
        path: ./wine-builds/wine*x86.tar.xz
